name: checkhealth

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      pr_number:
        description: "The pull request number to target"
        required: true
        type: string

jobs:
  checkhealth:
    runs-on: ubuntu-latest

    steps:
      - name: pr-info
        id: pr-info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PR_NUMBER="${{ github.event.inputs.pr_number }}"
            PR_DATA=$(gh pr view $PR_NUMBER --json headRefOid,baseRefName,headRepositoryUrl)
            COMMIT_SHA=$(echo "$PR_DATA" | jq -r '.headRefOid')
            REPO_URL=$(echo "$PR_DATA" | jq -r '.headRepositoryUrl')
            echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
            echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

            git remote add pr_target $REPO_URL
            git fetch pr_target
            git reset --hard $COMMIT_SHA
          else
            COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
            echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
            echo "Targeting PR triggered automatically."
          fi
          echo "Targeting commit: $COMMIT_SHA"

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.COMMIT_SHA }}
      
      - name: nix
        uses: cachix/install-nix-action@v22
        with:
          install_url: https://releases.nixos.org/nix/nix-2.15.1/install

      - name: build
        run: |-
          nix build .#neovim -o neovim_app
          echo "Neovim flake built successfully."

      - name: :checkhealth
        id: checkhealth
        run: |-
          ./neovim_app/bin/nvim --headless +"checkhealth" +qa > checkhealth_output.txt || true
          echo "CHECKHEALTH_OUTPUT<<EOF" >> $GITHUB_ENV
          cat checkhealth_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: comment
        uses: peter-evans/commit-comment@v2
        with:
          repository: ${{ github.repository }}
          sha: ${{ env.COMMIT_SHA }}
          body: |-
            ### Neovim :checkhealth Output
            ```
            ${{ env.CHECKHEALTH_OUTPUT }}
            ```